# Generated by Django 4.0.2 on 2022-02-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0002_remove_user_description_user_age_user_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.TextField(default='00000000', primary_key=True, serialize=False),
        ),
    ]
