# Generated by Django 4.0.2 on 2022-02-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0005_alter_user_age_alter_user_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
