# Generated by Django 3.2.12 on 2022-02-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0006_user_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('eventDate', models.DateTimeField()),
                ('eventDifficulty', models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Demanding'), ('4', 'Very Demanding')], max_length=1)),
                ('eventDescription', models.TextField()),
                ('eventLocation', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
            ],
        ),
    ]
