# Generated by Django 3.2.12 on 2022-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventArea',
            field=models.CharField(choices=[('1', 'Trondheim'), ('2', 'Oslo'), ('3', 'Stavanger'), ('4', 'Bergen')], default='1', max_length=1),
        ),
    ]
