# Generated by Django 4.0.2 on 2022-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0008_event_eventarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventSize',
            field=models.IntegerField(default=0),
        ),
    ]
