# Generated by Django 4.0.2 on 2022-02-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0009_auto_20220224_1330'),
        ('stili', '0009_event_eventsize'),
    ]

    operations = [
    ]
