# Generated by Django 4.0.2 on 2022-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0010_merge_0009_auto_20220224_1330_0009_event_eventsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialUser',
            fields=[
                ('orgNumber', models.TextField(primary_key=True, serialize=False)),
                ('orgName', models.CharField(max_length=100, unique=True)),
                ('location', models.TextField()),
                ('password', models.TextField()),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
