# Generated by Django 4.0.2 on 2022-03-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0010_merge_0009_auto_20220224_1330_0009_event_eventsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organizer_id',
        ),
    ]
