# Generated by Django 4.0.2 on 2022-03-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0012_rename_hours_event_eventdistance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer_id',
            new_name='organizer',
        ),
    ]
