# Generated by Django 4.0.2 on 2022-03-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0013_rename_organizer_id_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
