# Generated by Django 4.0.2 on 2022-03-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0015_alter_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventArea',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
