# Generated by Django 4.0.2 on 2022-03-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0011_commercialuser'),
        ('stili', '0016_remove_event_eventarea_alter_event_eventid'),
    ]

    operations = [
    ]
