# Generated by Django 4.0.2 on 2022-03-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0017_merge_20220315_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Mediocre'), ('3', 'Veteran')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('1', 'Trondheim'), ('2', 'Oslo'), ('3', 'Stavanger'), ('4', 'Bergen')], max_length=100),
        ),
    ]
