# Generated by Django 4.0.2 on 2022-03-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0012_eventparticipation'),
        ('stili', '0018_alter_user_experience_alter_user_location'),
    ]

    operations = [
    ]
