# Generated by Django 4.0.2 on 2022-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0019_merge_20220322_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventParticipation',
        ),
        migrations.AddField(
            model_name='event',
            name='eventParticipants',
            field=models.TextField(default=''),
        ),
    ]
