# Generated by Django 4.0.2 on 2022-03-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0020_delete_eventparticipation_event_eventparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commercialOrganizer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventParticipants',
            field=models.TextField(blank=True, default=''),
        ),
    ]
