# Generated by Django 4.0.2 on 2022-03-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0023_alter_event_commercialorganizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='commercialOrganizer',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='stili.commercialuser'),
        ),
    ]
