# Generated by Django 4.0.2 on 2022-03-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stili', '0025_alter_event_commercialorganizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organizer_id',
        ),
    ]
